Fixed translation error for the shaft generator.
age-series/ElectricalAge pull request #339
Opened 2024-07-21 23:08 UTC by TheBuilderBoy76

Line 434 in the `en_US.lang` file (`Converts_mechanical_energy_into_electricity,_or_(badly)_vice_versa.`) was mistakenly translated to Chinese instead of English.

2024-07-21 23:32 UTC, bloxgate requested changes

2024-07-21 23:32 UTC, bloxgate commented on src/main/resources/assets/eln/lang/en_US.lang
> +Converts_mechanical_energy_into_electricity,_or_(badly)_vice_versa.=Converts_mechanical_energy_into_electricity,_or_(badly)_vice_versa.
Shouldn't the later half of this actually have the spaces and such in it rather than _, like the entries below?

2024-07-21 23:39 UTC, jrddunbr requested changes
Small issue with the tag being replicated, instead of the translation being provided.

To explain a bit further the format of `.lang` files:

The translation function replaces `%1` with the variable provided in the code, so if my code has `%1` as "56" then this is how that may work:

`My_string_is_%1=My string is %1.` provides `My string is 56.`

Thankfully, in English, it's pretty easy to explain what the tags do because English is really flexible in the order you say things. But, in some languages, the structure might be different. Let's say that the above sentence structure is invalid in some language. We may have to write instead (notice the translation key on the left stays the same from before):

`My_string_is_%1=%1 is my string.` provides `56 is my string.`

This system allows that flexibility in the translation.

2024-07-21 23:39 UTC, jrddunbr commented on src/main/resources/assets/eln/lang/en_US.lang
> +Converts_mechanical_energy_into_electricity,_or_(badly)_vice_versa.=Converts_mechanical_energy_into_electricity,_or_(badly)_vice_versa.
`Converts mechanical energy into electricity, or (badly) vice versa.` is what should be on the right side of the equal sign. The left side of the translation file is the "tag" that the translator uses (and it escapes spaces and certain variables) and the right side is the final translation plus the variable tags.

2024-07-22 00:34 UTC, jrddunbr commented
I'm approving, and doing a squash merge.

2024-07-22 00:34 UTC, merged